### ISSUE TITLE
Magic links sent through some apps appear broken

### ISSUE THREAD

**Issue by aaemnnosttv** [aaemnnosttv/wp-cli-login-command#1]
Some apps which try to load previews of the url you are sharing (eg: Slack) will "break" the link when sharing because the preview triggers the login which will only work once.

**Comment by aaemnnosttv** [comment]
One workaround, at least for Slack, is to enclose the link in back ticks when sending.

Like so:
```
`http://example.com/some-magic-login-url`
```

Links within back ticks do not load a preview, while still preserving the behavior of a hyperlink.

**Comment by niladam** [comment]
Some other workarounds:

1. Send the email as plaintext, making sure the link is just text -- so that it's not scanned.
2. Send the email as html, but make sure the link is just text.

**Comment by aaemnnosttv** [comment]
@niladam are there any email clients you are aware of that preview hyperlinks?

**Comment by aaemnnosttv** [comment]
Closing this as it hasn't been much of an issue for most, as far as I can tell.
