### ISSUE TITLE
Allow companion plugin to be used as must-use plugin

### ISSUE THREAD

**Issue by viktorix** [aaemnnosttv/wp-cli-login-command#14]
To prevent accidental deletion of the companion plugin, it would be nice to be able to place it inside "mu-plugins" folder. I tried manually moving it there, but it's not being recognized and WP-CLI asks for companion plugin to be installed.

Maybe simply passing `--mu` to let WP-CLI know where to look for companion plugin.

Thanks!

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion @viktorix.  This could already be done if you were installing the plugin with Composer by overriding the install path for the package.

I'll see if there's a good way to implement this with the command.

**Comment by austinginder** [comment]
Looking over the code for the new mu-plugin feature, it appears this is still relies on `wp-cli-login-command` wp package to be installed. My ideal would be a standalone mu-plugin which I could deploy to remote sites as needed. My use case is with [Anchor Hosting](https://anchor.host) where I manage [a lot](https://anchor.host/tech-stack/) of WordPress sites. It would great if I could give my myself & customers a quick login link without requiring the wp package. Packages unfortunately don't yet persist with [WP Engine's SSH](https://wpengine.com/support/getting-started-ssh-gateway/). However I can easily upload a single file mu-plugin which in theory could allow for both `wp login` cli and the magic links.

After playing around with the code it looks like it is possible to just combine all of the needed classes into one really nasty single php file. I might just do that for my use case.

**Comment by aaemnnosttv** [comment]
You might be able to include the package as a local dependency rather than installed globally via wp-cli. I hear you on the single file drop-in although I don't think that's a need for most users of the package. You might consider forking it and modifying for your needs. I would be open to considering  PR too if the solution wasn't nasty :)

**Comment by austinginder** [comment]
Hmm so it looks like [One Time Login](https://github.com/danielbachhuber/one-time-login) will do preciously just that with a simple plugin install. Going to use that rather then taking your beautiful code and muddy it up.

**Comment by aaemnnosttv** [comment]
Haha, thanks. I plan for v2 to be primarily housed in a plugin, but not sure exactly when I'll get to that 😄 

Cheers!
