### ISSUE TITLE
Suggestion adding plugin to wpackagist?

### ISSUE THREAD

**Issue by djdesign** [aaemnnosttv/wp-cli-login-command#2]
Suggestion adding plugin to wpackagist?

**Comment by aaemnnosttv** [comment]
That would require publishing through WP.org which is unnecessary if you're already using Composer since you can pull in the plugin using [`aaemnnosttv/wp-cli-login-server`](https://packagist.org/packages/aaemnnosttv/wp-cli-login-server).
