### ISSUE TITLE
Link doesn't work locally

### ISSUE THREAD

**Issue by sjoerdvermeijden** [aaemnnosttv/wp-cli-login-command#21]
When I use the plugin locally i get a 404 error. I'm using mamp.
This was the link i got: http://dev.timber.nl/30734387/26320bcd-3f52ed-c3bc9df0

Thanks! Love the plugin

**Comment by aaemnnosttv** [comment]
Hmmm, that's strange. It definitely works locally, but there may be something about your environment which is throwing a wrench in things.

Try `wp login invalidate` and then try again by creating a new login link and see if that makes a difference for you?

**Comment by sjoerdvermeijden** [comment]
This is resolved. Thanks for the amazing package!

**Comment by aaemnnosttv** [comment]
Thanks, friend!
