### ISSUE TITLE
Customize --launch browser

### ISSUE THREAD

**Issue by Log1x** [aaemnnosttv/wp-cli-login-command#23]
Does there happen to be a way to configure the `--launch` browser? Right now, it attempts to use `xdg-open` to launch `www-browser` on my Windows 10's Linux Subsystem but I'd rather it just use `firefox.exe` or detect an environment variable of what my default browser executable is.

```
Error: /usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
```

**Comment by aaemnnosttv** [comment]
You can set the `WP_CLI_LOGIN_LAUNCH_WITH` environment variable to override the binary used to launch the URL :)

**Comment by Log1x** [comment]
Thanks!

`export WP_CLI_LOGIN_LAUNCH_WITH="/mnt/c/Program\ Files/Mozilla\ Firefox/firefox.exe"` did the trick.

`sh` seems to return a blank `Error:` for whatever reason but it works nonetheless. :smile: 

![Screenshot](https://log1x.com/screenshots/2017-08-30_19-50-32_FIE46.png)
