### ISSUE TITLE
syntax error, unexpected 'class'

### ISSUE THREAD

**Issue by m615926** [aaemnnosttv/wp-cli-login-command#27]
Hello~

When I run 'wp login xxx', and It said syntax error, unexpected 'class' of aaemnnosttv/wp-cli-login-command/command.php on line 11. My wp cli version is latest. Did I do something wrong?

**Comment by aaemnnosttv** [comment]
Hi there, it sounds like an issue with the autoloader.

How did you install the package?

**Comment by m615926** [comment]
Hi,

I install package through wp package install.

I use the script below:

"/opt/plesk/php/7.2/bin/php -d memory_limit=512M "$(which wp)" package install aaemnnosttv/wp-cli-login-command”

Is it correct?

感謝您的支持，有任何問題歡迎與我們聯絡!
服務時間：星期一～星期五 10:00～19:00
—
WordPress 顧問 - 賴俊吾 Oberon Lai
© 2018 Hellowp

**Comment by aaemnnosttv** [comment]
Yes that looks correct.

Are you sure you are executing the `wp login xxx` command with PHP version 5.5 or higher? The error you are citing looks like a pre-5.5 error. I see you are installing the command with PHP 7.2, but what do you see when you run `wp --info` without specifying the full path to the php binary?

**Comment by m615926** [comment]
You got it. My php version is 5.4. I will upgrade my php version. Thanks for help!

感謝您的支持，有任何問題歡迎與我們聯絡!
服務時間：星期一～星期五 10:00～19:00
—
WordPress 顧問 - 賴俊吾 Oberon Lai
© 2018 Hellowp

**Comment by aaemnnosttv** [comment]
Glad we were able to figure it out 😄 Cheers!
