### ISSUE TITLE
Magic login authentication failed. - 

### ISSUE THREAD

**Issue by JeffCleverley** [aaemnnosttv/wp-cli-login-command#28]
Getting this

`Magic login authentication failed.`

I have uninstalled and reinstalled the plugin. 

The site is a clone of another site on another server that is working fine. I have uninstalled the plugin, cleared wp-cli cache, reinstalled the plugin, and still getting this.

We use the plugin for SSO from our SaaS dashboard.

Any ideas?

**Comment by aaemnnosttv** [comment]
Hey there, I realize this is a bit late, but are you still having a problem with this? If so, could you elaborate on how this site is a clone of another one?

**Comment by aaemnnosttv** [comment]
Closing for now due to inactivity. Feel free to re-open if you have more information 😄

**Comment by eriteric** [comment]
I also get the "Magic login authentication failed" error, using wp-cli-login-command 1.3.0 with roots/trellis cloned today (WP-CLI 2.4.0). Command entered was: "wp login create username"
wp-cli-login-command 1.2.0 works fine.

**Comment by aaemnnosttv** [comment]
@eriteric do you have steps I can take to reproduce this consistently? If so, please open it as a new issue with as much detail as you can provide. Thanks!
