### ISSUE TITLE
WP-CLI outputs a wp-cli-login link for any command - plugin, theme, option etc

### ISSUE THREAD

**Issue by JeffCleverley** [aaemnnosttv/wp-cli-login-command#29]
I have some client sites where no matter the wp-cli command it will output the same wp login link

As in wp-cli will only output a link from this package, no matter what.

**Comment by aaemnnosttv** [comment]
That's rather strange. Can you give me a bit more context? Maybe output from a different command including the `--debug` flag?

**Comment by aaemnnosttv** [comment]
Closing this one out as unreproducible for now. Feel free to reopen with more information about the specific environments where you're seeing this issue.
