### ISSUE TITLE
Email i18n

### ISSUE THREAD

**Issue by tersor** [aaemnnosttv/wp-cli-login-command#31]
Hello.

What a great plugin this is!
It would have been nice to be able to translate the email, especially the [subject field](https://github.com/aaemnnosttv/wp-cli-login-command/blob/650daf069a2621fb0cd2994b25acec311d3b8da1/src/LoginCommand.php#L545).
Probably not necessary for the mustache template, huh?

**Comment by aaemnnosttv** [comment]
Hi there, and thanks for the kind words!

I agree, translation would be great, and not something that was considered initially. I think for now, your best bet is to copy the mustache template and translate it in the copy. Then you can pass the alternate template as an argument to `wp login email <user> --template=<path-to-template-file>`.

You can update the default by setting this in your `wp-cli.yml` or global config file like so

```yml
login email:
  template: path/to/alternate/template.mustache
```

Let me know if/how that works for you or if you have any other questions or suggestions.

**Comment by tersor** [comment]
Yes, the email body can be translated like you describe, works great! But how about the email **subject**?

**Comment by aaemnnosttv** [comment]
Oh! My mistake. You're right, there's currently no way to translate that. How about a new parameter to the `email` command?

Would this work for you?
```
wp login email <user> --subject='Alternate subject for login to {{domain}}' --template=...
```

**Comment by tersor** [comment]
That would work perfect!

**Comment by aaemnnosttv** [comment]
Great! I'll plan on adding this soon unless you'd like to submit a PR yourself?

**Comment by tersor** [comment]
Sure, I can try to submit a PR, thanks!
