### ISSUE TITLE
wp-cli.org Package Index Has Old Version

### ISSUE THREAD

**Issue by fluxism** [aaemnnosttv/wp-cli-login-command#37]
The wp-cli.org Package Index has an out of date version. I noticed this since the --redirect-url option is absent.

**Comment by aaemnnosttv** [comment]
Yes, this is a known issue that I ran into with another package a while back. I thought @schlessera had removed my packages from the package index though since the index isn't actively updated anymore and my packages are all available on Packagist. I will follow up with him about this 👍

**Comment by aaemnnosttv** [comment]
This is now fixed 🎉  See https://github.com/wp-cli/package-index/pull/121
