### ISSUE TITLE
Incompatible with trailing slash rewriterule (Apache)

### ISSUE THREAD

**Issue by rgbkgb** [aaemnnosttv/wp-cli-login-command#40]
Hello,
Thanks for your awesome work !
However, the magic link URL is not working properly because we have an apache rewriterule adding a trailing slash, then it leads to a 404.
Do you have any idea about how we could mitigate this issue ? 
Maybe we could change the source code in order to add a trailing slash to your magic link URL ?
Thanks in advance for your help !

Arthur

**Comment by rgbkgb** [comment]
We've added a RewriteCond to our .htaccess in order to not add a trailing slash to the magicUrl, however we are using CloudFlare, and it redirects us to the homepage.
We have made extensive testing and this behaviour is related to CloudFlare :/

**Comment by elindydotcom** [comment]
@rgbkgb - do you know if this is still an issue with Cloudflare?  Was looking at this project as an option to meet a need but Cloudflare is a must. So was just wondering if this is still an issue for you or if you found a workaround inside cloudflare.

**Comment by aaemnnosttv** [comment]
Thanks @jcatello – is the trailing slash applied as a redirect on the web server in that case or filtered into the URL WP generates?

**Comment by jcatello** [comment]
Its a redirect applied by the webserver, typically for WP Rocket users:

https://docs.wp-rocket.me/article/131-redirection-to-enforce-trailing-slash-on-urls#trailing-slashes-on-nginx-servers

**Comment by jcatello** [comment]
https://github.com/aaemnnosttv/wp-cli-login-command/pull/58 Do you want to review this?

**Comment by aaemnnosttv** [comment]
Planning on addressing this soon. Working on updating CI infra first before merging other changes.
