### ISSUE TITLE
Composer 2 issue

### ISSUE THREAD

**Issue by danharper83** [aaemnnosttv/wp-cli-login-command#44]
Composer 2 requires senver ^3.0 but this plugin requires ^1.0

Not sure if it works with latest version of semver or not but to make it install with all versions 

`(^1.4 || ^2 || ^3) `

Would fix it, this is what is happening in wp-cli/core-command

Cheers Dan

**Comment by aaemnnosttv** [comment]
Will do, thanks for the heads up!
