### ISSUE TITLE
Login command not working using mu-plugin

### ISSUE THREAD

**Issue by oxyc** [aaemnnosttv/wp-cli-login-command#45]
Seems the plugin version ensure check doesnt look at the mu-plugin path.

https://github.com/aaemnnosttv/wp-cli-login-command/blob/master/src/LoginCommand.php#L471

**Comment by aaemnnosttv** [comment]
Hi there! Are you experiencing a problem? If you follow the method that you linked there, you should see that it checks for the mu-plugin first.

**Comment by oxyc** [comment]
Aah sorry, I missed that. 

I'm guessing it's because I used composer installers to move it into the mu-plugin folder.

```json

    "installer-paths": {
      "web/app/mu-plugins/{$name}/": [
         "type:wordpress-muplugin",
         "aaemnnosttv/wp-cli-login-server"
       ],
```

But that makes puts it in a subdirectory `mu-plugins/wp-cli-login-server/wp-cli-login-server.php` so the mustUse existance check fails since it assumes it's a single file.

That's fine though, I can do it with the drop-in installer instead.
