### ISSUE TITLE
Alternative installation methods

### ISSUE THREAD

**Issue by blairwigleyactu** [aaemnnosttv/wp-cli-login-command#53]
WP Engine prevent the installation of WP CLI packages via their CLI, so I've been unable to install this package.

GF Forms have a cli offering that can be installed as a plugin: https://github.com/gravityforms/gravityformscli 

I'm just wondering if there's a way to install this without running `wp package install aaemnnosttv/wp-cli-login-command` e.g. via a plugin like the above?

**Comment by aaemnnosttv** [comment]
You could create your own plugin that installs/bundles the login command via Composer. There isn't an existing installable yet that I know of you could do this with but it would be quite simple to do so:

`composer.json`

```json
{
	"require": {
		"aaemnnosttv/wp-cli-login-command": "@stable"
	}
}
```

`plugin.php`

```php
<?php
/**
 * Plugin Name: WP CLI Login
 */

require_once __DIR__ . '/vendor/autoload.php';

```

Then you just need to run `composer install --no-dev` in the plugin directory and you should be all set – just activate in WP.

**Comment by blairwigleyactu** [comment]
Sorry forgot to thank you for your reply, got sidetracked with other projects but I'll be looking at this shortly - can't see a reason why it wouldn't work.
