### ISSUE TITLE
Honor `url` flag

### ISSUE THREAD

**Issue by entr** [aaemnnosttv/wp-cli-login-command#6]
When I try to pass a url using the `--url` flag it doesn't seem to make any difference.

```
$ wp --version
WP-CLI 0.24.1

$ wp core version
4.6.1

$ php --version
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
```

**Comment by aaemnnosttv** [comment]
Hey thanks for the report. 

Would you please provide a little more detail about the context, how to reproduce this, and what is expected?

**Comment by entr** [comment]
It's simple really.

> --url=<url>
Pretend request came from given URL. In multisite, this argument is how the target site is specified.
> -from wp-cli docs

So if one do `$ wp login as adm1n --url=localhost:8080` (s)he you would expect the generated login url to be `http://localhost:8080/df28230f/b1a61d228c-63e276ea-151b5a3k/`

Imagine you ran `$ wp server` and want to generate a link for it. Hope that makes sense. Cheers.

**Comment by aaemnnosttv** [comment]
Care to give #15 a test and see if that works for you?

**Comment by entr** [comment]
Working for me. Thanks!
