### ISSUE TITLE
WP login command slow, 1-10 seconds

### ISSUE THREAD

**Issue by Luke-SF** [aaemnnosttv/wp-cli-login-command#64]
This plugin is working well for me but I noticed that the wp login command may take between one to ten seconds to complete. 

This is on a site that is generally responsive and working well (navigating to any /wp-admin/ dashboard page in a second or two). Is there something that could be optimized within login-command or WPCLI to make it less slow?

**Comment by aaemnnosttv** [comment]
It's likely something specific to the environment or the site's configuration – with a fresh site the process is very fast. I realize that isn't very helpful, but there are many things that could be responsible e.g. plugins hooking into `admin_init`, login actions, update checks, etc.

Can you observe similar performance when testing multiple magic links consecutively?
