### ISSUE TITLE
Unable to install the server plugin using Composer v2

### ISSUE THREAD

**Issue by thunderdw** [aaemnnosttv/wp-cli-login-command#65]
Hi there!

I'm attempting to install the server plugin via Composer using Composer v2.

Currently, the plugin can only be installed by Composer v1 due to its version dependency on `composer/installers`.
https://github.com/aaemnnosttv/wp-cli-login-command/blob/272effd321840b7d68cecbd4d99934b2a0e8aa2f/plugin/composer.json#L13-L15

I've made a basic change that allows the plugin to be installed by either Composer version thunderdw@1bd5699

If it would be welcome I'm happy to submit a PR

**Comment by aaemnnosttv** [comment]
Thanks for flagging! A PR would be great 👍

**Comment by thunderdw** [comment]
Great, just made one. Thanks!

**Comment by aaemnnosttv** [comment]
Thanks! I still need to publish the change to the server plugin's repo which is used by Composer but that should be done soon 👍

**Comment by thunderdw** [comment]
Awesome, thank you!
