### ISSUE TITLE
mu-plugins

### ISSUE THREAD

**Issue by stefanpejcic** [aaemnnosttv/wp-cli-login-command#71]
Hi, is it possible to create a flag for the install command so that instead of always putting the file in plugins we have an option to use mu-plugins instead?

Current:

```
wp-content/plugins/wp-cli-login-server/wp-cli-login-server.php
``` 

Preferred:
```
wp-content/mu-plugins/wp-cli-login-server.php
``` 

Cheers!

**Comment by aaemnnosttv** [comment]
Hey, thanks for the request! This flag actually already exists, I'm a bit surprised that it's missing in the README – sorry about that!

The command is

```
wp login install --mu
```

Cheers!

**Comment by stefanpejcic** [comment]
Great, thank you for the info 🙏
