### ISSUE TITLE
WP 4.7 Magic link always brings up "The attempted magic login has expired or already been used"

### ISSUE THREAD

**Issue by codemountain** [aaemnnosttv/wp-cli-login-command#8]
Since upgrade to WP 4.7, whenever i issue a wp login create username , i get a link and when we paste it in it comes up with the message like the link has been used. Look thur error logs did not find anything. Any clues?
Thanks.
Note: upgraded both server and client side packages to today's latest versions of wp-cli-login

**Comment by aaemnnosttv** [comment]
Sounds like something specific to your environment. I just tested this and wasn't able to replicate.

v1.1 which was just released ran its tests against 4.7 in the build as well, so I think it's safe to say that it is compatible with 4.7.

Not to say that you don't have a problem of course. Could you share some details about your setup?

Also, when you say you're pasting it in, I assume you mean pasting straight from your terminal to your browser.  Pasting the login link into an app like slack, or any other which tries to load a preview of the url you are sharing _will_ break the login link (see #1).

Ps. you can also save yourself the copy/paste by appending `--launch` to the `create` command.

**Comment by codemountain** [comment]
Thanks for the feedback:)
Think you are right, I have 2 almost identical sites on 4.7 and one of them the login URL works and the other the URL login doesn’t. and yes i paste directly in the browser for both. I’ll compare permissions, plugins and try to match to isolate issue. Is there an error log from the plugin that i can look at as well?
Thanks!

**Comment by aaemnnosttv** [comment]
Neither the command/plugin implements their own logs of any kind. If you're seeing the screen that looks like this:

![image](https://cloud.githubusercontent.com/assets/1621608/21190130/88cb510e-c229-11e6-84b9-2ba83d5c6296.png)

-- then I wouldn't expect there to be an error, as this is the intended behavior when trying to access a valid login link which has been used or expired.

If you find out what the problem is, by all means please let me know!

**Comment by codemountain** [comment]
Got it :-P code 18.. as most of the time.
Had a script automating old domain search and replace, it failed on the second site so siteurl option was not the right one and hence generating a link for the wrong domain. So plugin security = checked :-) thanks for the help.

**Comment by aaemnnosttv** [comment]
Thanks for for the follow up and sharing the cause 👍 

Cheers!
