### ISSUE TITLE
Configurable timeout for magic link ?

### ISSUE THREAD

**Issue by niladam** [aaemnnosttv/wp-cli-login-command#9]
I think it would be great to have the means to be able to configure the magic link timeout. Maybe via wp-cli.yml or via a command attribute ?

**Comment by niladam** [comment]
I opened pull request #12 that tackles this, using environment variable ***WP_CLI_LOGIN_TIMEOUT_DURATION*** as means to control the timeout link.

**Comment by aaemnnosttv** [comment]
Thanks for the suggestion, this is something I have thought about adding as well and I think it's definitely a reasonable request.

Thanks for the pull request too I will review that in just a minute and follow up with you there :)

**Comment by niladam** [comment]
You're most welcome. Initially i thought about going about reading the value from a global/local wp-cli.yml but when i was working on it i thought ENV would be easier to work with as you can always `export WP_CLI_LOGIN_TIMEOUT_DURATION=10` for example before running the command. Also, people could want this to be server-agnostic so it makes sense to have it like that..
